// Code generated by protoc-gen-go. DO NOT EDIT.
// source: products.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Product struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price                float32  `protobuf:"fixed32,4,opt,name=price,proto3" json:"price,omitempty"`
	Rate                 int64    `protobuf:"varint,5,opt,name=rate,proto3" json:"rate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c6e54f42122eb82, []int{0}
}

func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (m *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(m, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Product) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Product) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Product) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Product) GetRate() int64 {
	if m != nil {
		return m.Rate
	}
	return 0
}

type GetProductRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProductRequest) Reset()         { *m = GetProductRequest{} }
func (m *GetProductRequest) String() string { return proto.CompactTextString(m) }
func (*GetProductRequest) ProtoMessage()    {}
func (*GetProductRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c6e54f42122eb82, []int{1}
}

func (m *GetProductRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductRequest.Unmarshal(m, b)
}
func (m *GetProductRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductRequest.Marshal(b, m, deterministic)
}
func (m *GetProductRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductRequest.Merge(m, src)
}
func (m *GetProductRequest) XXX_Size() int {
	return xxx_messageInfo_GetProductRequest.Size(m)
}
func (m *GetProductRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductRequest proto.InternalMessageInfo

func (m *GetProductRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetProductResponse struct {
	Product              *Product `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProductResponse) Reset()         { *m = GetProductResponse{} }
func (m *GetProductResponse) String() string { return proto.CompactTextString(m) }
func (*GetProductResponse) ProtoMessage()    {}
func (*GetProductResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c6e54f42122eb82, []int{2}
}

func (m *GetProductResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductResponse.Unmarshal(m, b)
}
func (m *GetProductResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductResponse.Marshal(b, m, deterministic)
}
func (m *GetProductResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductResponse.Merge(m, src)
}
func (m *GetProductResponse) XXX_Size() int {
	return xxx_messageInfo_GetProductResponse.Size(m)
}
func (m *GetProductResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductResponse proto.InternalMessageInfo

func (m *GetProductResponse) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

func init() {
	proto.RegisterType((*Product)(nil), "package.name.Product")
	proto.RegisterType((*GetProductRequest)(nil), "package.name.GetProductRequest")
	proto.RegisterType((*GetProductResponse)(nil), "package.name.GetProductResponse")
}

func init() {
	proto.RegisterFile("products.proto", fileDescriptor_8c6e54f42122eb82)
}

var fileDescriptor_8c6e54f42122eb82 = []byte{
	// 236 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0x41, 0x4b, 0x03, 0x31,
	0x10, 0x85, 0xd9, 0xb4, 0xb5, 0x3a, 0x95, 0x82, 0x83, 0x42, 0xe8, 0xc5, 0xb0, 0x5e, 0xf6, 0x62,
	0x16, 0xea, 0x3f, 0x10, 0xc4, 0xa3, 0x92, 0xa3, 0x9e, 0x62, 0x32, 0x48, 0x10, 0x37, 0x31, 0x49,
	0x05, 0xff, 0xbd, 0x34, 0xbb, 0x8b, 0x2b, 0xa5, 0xa7, 0x4c, 0xde, 0x7c, 0x99, 0xbc, 0x79, 0xb0,
	0x0e, 0xd1, 0xdb, 0x9d, 0xc9, 0x49, 0x86, 0xe8, 0xb3, 0xc7, 0xf3, 0xa0, 0xcd, 0x87, 0x7e, 0x27,
	0xd9, 0xe9, 0x4f, 0xaa, 0x7f, 0x60, 0xf9, 0xdc, 0xf7, 0x71, 0x0d, 0xcc, 0x59, 0x5e, 0x89, 0xaa,
	0x39, 0x53, 0xcc, 0x59, 0x44, 0x98, 0xef, 0x11, 0xce, 0x8a, 0x52, 0x6a, 0x14, 0xb0, 0xb2, 0x94,
	0x4c, 0x74, 0x21, 0x3b, 0xdf, 0xf1, 0x59, 0x69, 0x4d, 0x25, 0xbc, 0x84, 0x45, 0x88, 0xce, 0x10,
	0x9f, 0x8b, 0xaa, 0x61, 0xaa, 0xbf, 0xec, 0x67, 0x45, 0x9d, 0x89, 0x2f, 0x44, 0xd5, 0xcc, 0x54,
	0xa9, 0xeb, 0x1b, 0xb8, 0x78, 0xa4, 0x3c, 0xfc, 0xae, 0xe8, 0x6b, 0x47, 0xe9, 0xc0, 0x44, 0xfd,
	0x00, 0x38, 0x85, 0x52, 0xf0, 0x5d, 0x22, 0x6c, 0x61, 0x39, 0x6c, 0x55, 0xd0, 0xd5, 0xf6, 0x4a,
	0x4e, 0xb7, 0x92, 0x23, 0x3f, 0x52, 0xdb, 0x57, 0x38, 0x1d, 0xb4, 0x84, 0x4f, 0x00, 0x7f, 0x23,
	0xf1, 0xfa, 0xff, 0xcb, 0x03, 0x47, 0x1b, 0x71, 0x1c, 0xe8, 0xdd, 0xdc, 0x6f, 0x5e, 0xb8, 0x6c,
	0xc7, 0x94, 0x6f, 0x13, 0xc5, 0x6f, 0x67, 0xa8, 0x2d, 0x69, 0xbf, 0x9d, 0x94, 0xe3, 0xee, 0x37,
	0x00, 0x00, 0xff, 0xff, 0x27, 0x32, 0x10, 0xcc, 0x86, 0x01, 0x00, 0x00,
}
